project(redhat)

if (APPLICATION_FLAVOR_REDHAT_PKI_THEME)
    # compute certificate system name
    set(CERTIFICATE_SYSTEM_THEME "Red Hat")
    set(CERTIFICATE_SYSTEM_BATCH_UPDATE_VERSION "")
    if ("${APPLICATION_VERSION}" STREQUAL "10.5.1")
        set(CERTIFICATE_SYSTEM_VERSION "9.3")
    elseif ("${APPLICATION_VERSION}" STREQUAL "10.5.9")
        set(CERTIFICATE_SYSTEM_VERSION "9.4")
        set(CERTIFICATE_SYSTEM_BATCH_UPDATE_VERSION " (Batch Update 3)")
    elseif ("${APPLICATION_VERSION}" STREQUAL "10.5.16")
        set(CERTIFICATE_SYSTEM_VERSION "9.5")
        set(CERTIFICATE_SYSTEM_BATCH_UPDATE_VERSION " (Batch Update 4)")
    elseif ("${APPLICATION_VERSION}" STREQUAL "10.5.17")
        set(CERTIFICATE_SYSTEM_VERSION "9.6")
    elseif ("${APPLICATION_VERSION}" STREQUAL "10.5.18")
        set(CERTIFICATE_SYSTEM_VERSION "9.7")
        set(CERTIFICATE_SYSTEM_BATCH_UPDATE_VERSION " (Batch Update 8)")
    elseif ("${APPLICATION_VERSION_MAJOR}.${APPLICATION_VERSION_MINOR}" STREQUAL "10.5")
        set(CERTIFICATE_SYSTEM_VERSION "9")
    elseif ("${APPLICATION_VERSION_MAJOR}.${APPLICATION_VERSION_MINOR}" STREQUAL "10.6")
        set(CERTIFICATE_SYSTEM_VERSION "10")
    else()
        set(CERTIFICATE_SYSTEM_VERSION "")
    endif()
    set(CERTIFICATE_SYSTEM_NAME "${CERTIFICATE_SYSTEM_THEME} Certificate System ${CERTIFICATE_SYSTEM_VERSION}${CERTIFICATE_SYSTEM_BATCH_UPDATE_VERSION}")

    add_subdirectory(common-ui)
    add_subdirectory(console-ui)
endif (APPLICATION_FLAVOR_REDHAT_PKI_THEME)
